# Generated by Django 5.1.15 on 2026-10-08 20:50

import apps.reminders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("tv", "TV")], max_length=5
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "season_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "remind_on",
                    models.CharField(
                        choices=[
                            ("release_day", "On release day"),
                            ("one_day_before", "One day before"),
                            ("one_week_before", "One week before"),
                        ],
                        default="release_day",
                        max_length=16,
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=apps.reminders.models.default_channels,
                        validators=[apps.reminders.models.validate_channels],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("last_known_release_date", models.DateField(blank=True, null=True)),
                (
                    "release_date_changed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_known_release_date", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "media_type", "tmdb_id"),
                        name="uniq_reminder_per_title",
                    )
                ],
            },
        ),
    ]
