# Generated by Django 5.1.15 on 2026-10-08 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotebookShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("ratings", "Status and ratings"),
                            ("ratings_notes", "Status, ratings and notes"),
                        ],
                        default="ratings",
                        max_length=14,
                    ),
                ),
                ("statuses", models.JSONField(blank=True, default=list)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=40)),
                ("bio", models.CharField(blank=True, max_length=200)),
                (
                    "avatar_kind",
                    models.CharField(
                        choices=[
                            ("initial", "Initial letter"),
                            ("poster", "Favourite title's poster"),
                        ],
                        default="initial",
                        max_length=8,
                    ),
                ),
                ("avatar_poster_path", models.CharField(blank=True, max_length=255)),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("private", "Only me"),
                            ("unlisted", "Anyone with the link"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=8,
                    ),
                ),
                ("show_stats", models.BooleanField(default=False)),
                ("username_changed_at", models.DateTimeField(blank=True, null=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=16, unique=True)),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("is_ranked", models.BooleanField(default=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Only me"),
                            ("unlisted", "Anyone with the link"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=8,
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker", "blocked"), name="uniq_block"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("profile", "Profile"), ("list", "List")], max_length=8
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("abuse", "Insult / hate"),
                            ("spam", "Spam / advertising"),
                            ("impersonation", "Impersonation / fake account"),
                            ("personal_info", "Sharing personal information"),
                            ("other", "Other"),
                        ],
                        max_length=14,
                    ),
                ),
                ("details", models.CharField(blank=True, max_length=200)),
                ("counts", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["resolved_at", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reporter", "target_type", "target_id"),
                        name="uniq_report",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_type", models.CharField(max_length=5)),
                ("tmdb_id", models.PositiveIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                ("comment", models.CharField(blank=True, max_length=280)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("poster_path", models.CharField(blank=True, max_length=255)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("snapshot_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="social.userlist",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_list", "position"), name="uniq_list_position"
                    ),
                    models.UniqueConstraint(
                        fields=("user_list", "media_type", "tmdb_id"),
                        name="uniq_list_title",
                    ),
                ],
            },
        ),
    ]
