# Generated by Django 5.1.15 on 2026-10-08 20:39

import apps.collections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name_tr", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80)),
                ("description_tr", models.CharField(blank=True, max_length=240)),
                ("description_en", models.CharField(blank=True, max_length=240)),
                (
                    "reason_tr",
                    models.CharField(
                        blank=True,
                        help_text="Spoiler içermemeli (ör. Tersköşe).",
                        max_length=160,
                    ),
                ),
                ("reason_en", models.CharField(blank=True, max_length=160)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="An emoji, e.g. 🍿", max_length=8
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("tv", "TV"), ("both", "Both")],
                        default="movie",
                        max_length=5,
                    ),
                ),
                (
                    "recipe",
                    models.JSONField(
                        default=dict,
                        help_text="Rule the list is generated from; see apps/collections/recipe.py.",
                        validators=[apps.collections.models.validate_recipe],
                    ),
                ),
                (
                    "editor_pins",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Shown first, in this order: ["movie:550", "tv:1396"]',
                        validators=[apps.collections.models.validate_title_keys],
                    ),
                ),
                (
                    "editor_blocklist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Never shown: ["movie:550"]',
                        validators=[apps.collections.models.validate_title_keys],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "slug"],
            },
        ),
    ]
