# Generated by Django 5.1.15 on 2026-10-08 21:05

import apps.notebook.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotebookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("tv", "TV")], max_length=5
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("want_to_watch", "Want to watch"),
                            ("watching", "Watching"),
                            ("watched", "Watched"),
                            ("dropped", "Dropped"),
                        ],
                        db_index=True,
                        max_length=14,
                        null=True,
                    ),
                ),
                ("is_favorite", models.BooleanField(db_index=True, default=False)),
                (
                    "rating_x2",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=5000)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.notebook.models.validate_tags],
                    ),
                ),
                ("watched_on", models.DateField(blank=True, null=True)),
                ("rewatch_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "progress_season",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "progress_episode",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("original_title", models.CharField(blank=True, max_length=255)),
                ("poster_path", models.CharField(blank=True, max_length=255)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("genres", models.JSONField(blank=True, default=list)),
                ("runtime_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_runtime", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_count", models.PositiveIntegerField(blank=True, null=True)),
                ("snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "notebook entries",
                "ordering": ["-updated_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "media_type", "tmdb_id"),
                        name="uniq_notebook_entry",
                    )
                ],
            },
        ),
    ]
