# Generated by Django 5.1.15 on 2026-10-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookentry",
            name="note_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notebookentry",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Only me"), ("public", "Public")],
                default="private",
                max_length=8,
            ),
        ),
    ]
