# Generated by Django 5.1.15 on 2026-10-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("movie_tmdb_id", models.IntegerField(blank=True, null=True)),
                ("tv_tmdb_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "profile_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("popularity", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-popularity"],
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("tv", "TV Show")], max_length=5
                    ),
                ),
                ("tmdb_id", models.IntegerField()),
                ("title", models.CharField(max_length=500)),
                ("title_en", models.CharField(blank=True, default="", max_length=500)),
                (
                    "original_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("overview", models.TextField(blank=True, default="")),
                ("overview_en", models.TextField(blank=True, default="")),
                (
                    "poster_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "backdrop_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "original_language",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("vote_average", models.FloatField(default=0.0)),
                ("vote_count", models.IntegerField(default=0)),
                ("popularity", models.FloatField(default=0.0)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("first_air_date", models.DateField(blank=True, null=True)),
                ("cached_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="titles", to="catalog.genre"
                    ),
                ),
            ],
            options={
                "ordering": ["-popularity"],
            },
        ),
        migrations.CreateModel(
            name="TVDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_seasons", models.IntegerField(default=0)),
                ("number_of_episodes", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                (
                    "episode_runtime",
                    models.IntegerField(
                        blank=True,
                        help_text="Average episode runtime in minutes",
                        null=True,
                    ),
                ),
                ("networks", models.JSONField(blank=True, default=list)),
                ("last_air_date", models.DateField(blank=True, null=True)),
                ("in_production", models.BooleanField(default=False)),
                (
                    "title",
                    models.OneToOneField(
                        limit_choices_to={"media_type": "tv"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tv_details",
                        to="catalog.title",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="title",
            index=models.Index(
                fields=["media_type", "tmdb_id"], name="catalog_tit_media_t_e4c9a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="title",
            index=models.Index(
                fields=["-vote_average"], name="catalog_tit_vote_av_a873e1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="title",
            unique_together={("media_type", "tmdb_id")},
        ),
    ]
