# Generated by Django 5.1.15 on 2026-10-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reminder_due", "Reminder due"),
                    ("release_date_changed", "Release date changed"),
                    ("content_hidden", "Content hidden after reports"),
                ],
                max_length=24,
            ),
        ),
    ]
