# Generated by Django 5.1.15 on 2026-10-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("provider", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=80)),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("parse", "Query parsing"),
                            ("explain", "Explanation"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("unavailable", "Unavailable (429/timeout/5xx)"),
                            ("bad_output", "Invalid output"),
                            ("error", "Other error"),
                        ],
                        max_length=12,
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=8, default=0, max_digits=12),
                ),
            ],
            options={
                "verbose_name": "LLM usage log",
                "ordering": ["-created_at"],
            },
        ),
    ]
