# Generated by Django 5.1.15 on 2026-10-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_llm_usage_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("day", models.DateField()),
                ("value", models.BigIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["day"], name="search_dail_day_d0fb48_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "day"), name="uniq_counter_key_day"
                    )
                ],
            },
        ),
    ]
